spring:
  datasource:
    url: jdbc:h2:mem:devfon://127.0.0.1:8080/console
    username: devfon
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false